//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QuanLyTienEntities : DbContext
    {
        public QuanLyTienEntities()
            : base("name=QuanLyTienEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<List_Name_HuiHeo> List_Name_HuiHeo { get; set; }
        public virtual DbSet<List_Name_TienGop> List_Name_TienGop { get; set; }
        public virtual DbSet<Detail_HuiHeo> Detail_HuiHeo { get; set; }
        public virtual DbSet<Detail_TienGop> Detail_TienGop { get; set; }
        public virtual DbSet<List_Remove_HuiHeo> List_Remove_HuiHeo { get; set; }
        public virtual DbSet<Detail_Remove_HuiHeo> Detail_Remove_HuiHeo { get; set; }
        public virtual DbSet<Detail_Remove_TienGop> Detail_Remove_TienGop { get; set; }
        public virtual DbSet<List_Remove_TienGop> List_Remove_TienGop { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
