//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTien
{
    using System;
    using System.Collections.Generic;
    
    public partial class Detail_Remove_HuiHeo
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Buoi { get; set; }
        public Nullable<int> SoTien { get; set; }
        public string GhiChu { get; set; }
        public Nullable<bool> Status { get; set; }
        public string TieuDe { get; set; }
    }
}
