//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyTien
{
    using System;
    using System.Collections.Generic;
    
    public partial class List_Name_TienGop
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string TieuDe { get; set; }
    }
}
